from combine_cumulative_tables import append_cumulative_table

# append_cumulative_table("EastWest",'1')
# append_cumulative_table("MSOE",'2')
# append_cumulative_table("DominicanIL",'3')
# append_cumulative_table("MoodyBible",'4')
# append_cumulative_table("WheatonIL",'5')
# append_cumulative_table("Roosevelt",'6')
# append_cumulative_table("Carthage",'7')
# append_cumulative_table("Wabash",'8')
# append_cumulative_table("Knox",'9')
# append_cumulative_table("Fontbonne",'10')
# append_cumulative_table("CornellCollege",'11')
# append_cumulative_table("Chicago",'12')
# append_cumulative_table("Albion",'13')
# append_cumulative_table("UWPlatteville",'14')
# append_cumulative_table("OlivetCollege",'15')
# append_cumulative_table("Kalamazoo",'16')
# append_cumulative_table("Rose-Hulman",'17')
# append_cumulative_table("NorthPark",'18')
# append_cumulative_table("GustavusAdolphus",'19')
# append_cumulative_table("IllinoisTech",'20')
append_cumulative_table("Trine",'21')
